Task01_BrainTumour:
  modalities: ['FLAIR', 'T1w', 'T1gd', 'T2w']
  in_channels: 4
  num_classes: 4
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task02_Heart:
  modalities: ['MRI']
  in_channels: 1
  num_classes: 2
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task03_Liver:
  modalities: ['CT']
  in_channels: 1
  num_classes: 3
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task04_Hippocampus:
  modalities: ['MRI']
  in_channels: 1
  num_classes: 3
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task05_Prostate:
  modalities: ['T2', 'ADC']
  in_channels: 2
  num_classes: 3
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task06_Lung:
  modalities: ['CT']
  in_channels: 1
  num_classes: 2
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task07_Pancreas:
  modalities: ['CT']
  in_channels: 1
  num_classes: 2
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task08_HepaticVessel:
  modalities: ['CT']
  in_channels: 1
  num_classes: 3
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task09_Spleen:
  modalities: ['CT']
  in_channels: 1
  num_classes: 2
  loss_function: 'CrossEntropy'
  slice_axis: 2

Task10_Colon:
  modalities: ['CT']
  in_channels: 1
  num_classes: 2
  loss_function: 'CrossEntropy'
  slice_axis: 2